### ISSUE TITLE
bulk update of time entries doesn't work 

### ISSUE THREAD

**Issue by ajeeshkumar** [dmp1ce/redmine-contracts-with-time-tracking-plugin#63]
When I try to run a bulk update on select time entries in a project, I get internal server error.

The production log shows the following error:

NoMethodError (undefined method `is_fixed_price' for nil:NilClass):
  plugins/contracts/lib/contracts/patches/time_entry_patch.rb:29:in `time_not_exceed_contract'
  app/controllers/timelog_controller.rb:185:in `block in bulk_update'
  app/controllers/timelog_controller.rb:181:in `each'
  app/controllers/timelog_controller.rb:181:in `bulk_update'
  lib/redmine/sudo_mode.rb:63:in `sudo_mode'

**Comment by archonwang** [comment]
@ajeeshkumar , you can try to use the fork of FireMartZ
https://github.com/upgradeya/redmine-contracts-with-time-tracking-plugin/

branch - master. 

please check it whether it work well.
